{% set name = "flax" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce2229a2ecb689678ba619e822346447c173c2ac1635e674e8249b97ed816cab

build:
  number: 0
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  # build:
  #   - python
  #   - pip
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - numpy >=1.23.2  # [py>=311]
    - numpy >=1.26.0  # [py>=312]
    # upstream requiers jax >=0.8.1 but we have 0.5.0 in channel
    - jax
    - msgpack-python
    - optax
    - orbax-checkpoint
    - tensorstore
    - rich >=11.1.0
    - typing_extensions >=4.2.0
    - pyyaml >=5.4.1
    - treescope >=0.1.7

test:
  imports:
    - flax
    - flax.configurations
    - flax.core
    - flax.cursor
    - flax.deprecated
    - flax.errors
    - flax.ids
    - flax.linen
    - flax.metrics
    - flax.nnx
    - flax.testing
    - flax.training
    - flax.traverse_util
    - flax.typing
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
  requires:
    - pip

about:
  home: https://github.com/google/flax
  summary: Flax A neural network library for JAX designed for flexibility
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: http://flax.readthedocs.io
  dev_url: https://github.com/google/flax

extra:
  recipe-maintainers:
    - pfackeldey
    - PhilipVinc
    - jheek
    - avital
    - levskaya
    - andsteing
    - gabrielcnr
    - traversaro
