{% set name = "flax" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce2229a2ecb689678ba619e822346447c173c2ac1635e674e8249b97ed816cab

build:
  number: 0
  # skip win: no tensorstore/orbax for win in channel
  skip: true  # [py<311 or win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python
    - numpy >=1.23.2  # [py>=311]
    - numpy >=1.26.0  # [py>=312]
    # TODO: rebiuld with jax >=0.8.1
    # upstream requiers jax >=0.8.1 but we have 0.7.x in channel
    - jax >=0.5.0,<0.8
    - msgpack-python
    - optax
    - orbax-checkpoint
    - tensorstore
    - rich >=11.1.0
    - typing_extensions >=4.2.0
    - pyyaml >=5.4.1
    - treescope >=0.1.7

test:
  source_files:
    - tests
  imports:
    - flax
    - flax.configurations
    - flax.core
    - flax.cursor
    - flax.errors
    - flax.ids
    - flax.linen
    - flax.metrics
    - flax.training
    - flax.traverse_util
    - flax.typing
  requires:
    - pip
    - pytest
    - pytest-xdist
    - tensorflow >=2.12.0   # [py<313]
    - tensorflow >=2.20.0   # [py>=313]
    - cloudpickle >=3.0.0
  commands:
    # TODO: rebiuld with jax >=0.8.1; enable nnx tests
    # pip check fails because upstream requires jax>=0.8.1,
    # but the current channel provides jax 0.7.x
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -v -n auto tests --ignore=tests/nnx

about:
  home: https://github.com/google/flax
  summary: Flax A neural network library for JAX designed for flexibility
  description: |
    Flax provides a flexible end-to-end user experience for researchers and 
    developers who use JAX for neural networks. Flax enables you to use the full power of JAX
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://flax.readthedocs.io
  dev_url: https://github.com/google/flax

extra:
  recipe-maintainers:
    - pfackeldey
    - PhilipVinc
    - jheek
    - avital
    - levskaya
    - andsteing
    - gabrielcnr
    - traversaro
