{% set name = "flax" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8a997afc5a482a5d7473586ad74113e3b067f1e19afcb8096ac482ecc780a59

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dataclasses
    - jax >=0.2.6
    - matplotlib-base
    - msgpack-python
    - numpy >=1.12
    - optax >=0.0.6

test:
  imports:
    - flax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/flax
  summary: 'Flax: A neural network library for JAX designed for flexibility'
  license: Apache-2.0
  license_file: LICENSE
  doc_url: http://flax.readthedocs.io
  dev_url: https://github.com/google/flax

extra:
  recipe-maintainers:
    - PhilipVinc
    - jheek
    - avital
    - levskaya
    - andsteing
